package io.github.dklages20.igdb.types.deserializers

import io.github.dklages20.igdb.types.AgeRatingContentDescriptionV2

class AgeRatingContentDescriptionV2Deserializer: IGDBObjectDeserializer<AgeRatingContentDescriptionV2>(AgeRatingContentDescriptionV2::class)
class AgeRatingContentDescriptionV2ListDeserializer: IGDBObjectListDeserializer<AgeRatingContentDescriptionV2>(AgeRatingContentDescriptionV2Deserializer())