package io.github.dklages20.igdb.types.deserializers

import io.github.dklages20.igdb.types.AgeRatingOrganization

class AgeRatingOrganizationDeserializer: IGDBObjectDeserializer<AgeRatingOrganization>(AgeRatingOrganization::class)
class AgeRatingOrganizationListDeserializer: IGDBObjectListDeserializer<AgeRatingOrganization>(AgeRatingOrganizationDeserializer())