package io.github.dklages20.igdb.types.deserializers

import io.github.dklages20.igdb.types.CollectionMembershipType

class CollectionMembershipTypeDeserializer: IGDBObjectDeserializer<CollectionMembershipType>(CollectionMembershipType::class)
class CollectionMembershipTypeListDeserializer: IGDBObjectListDeserializer<CollectionMembershipType>(CollectionMembershipTypeDeserializer())