package io.github.dklages20.igdb.types.deserializers

import io.github.dklages20.igdb.types.CollectionRelationType

class CollectionRelationTypeDeserializer : IGDBObjectDeserializer<CollectionRelationType>(CollectionRelationType::class)
class CollectionRelationTypeListDeserializer : IGDBObjectListDeserializer<CollectionRelationType>(CollectionRelationTypeDeserializer())