package io.github.dklages20.igdb.types.deserializers

import io.github.dklages20.igdb.types.PlatformVersionCompany

class PlatformVersionCompanyDeserializer: IGDBObjectDeserializer<PlatformVersionCompany>(PlatformVersionCompany::class)
class PlatformVersionCompanyListDeserializer: IGDBObjectListDeserializer<PlatformVersionCompany>(PlatformVersionCompanyDeserializer())